modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/InZan17/Unloaded-Activity-Fabric/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "unloaded_activity"
version = "${version}"
displayName = "Unloaded Activity"
authors = "Zan"
description = "Make certain blocks such as crops grow as if they've always grown when put into simulation distance."
logoFile = "assets/unloadedactivity/icon.png"

[[dependencies.unloaded_activity]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.unloaded_activity]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_versions}"
ordering = "NONE"
side = "SERVER"
